theme = "flatwhite"

[editor]
gutters = ["diagnostics", "spacer", "diff"]

[editor.lsp]
display-messages = true
display-inlay-hints = false
snippets = false

[keys.normal.space]
F = "file_picker_in_current_buffer_directory"

